export const farmerCopy = {
  nav: {
    home: "Home",
    maize: "My maize",
    offers: "Offers",
    payments: "Payments",
  },
  home: {
    eyebrow: "Your maize",
    welcome: "Welcome back",
    available: "Available maize",
    availableHint: "Quantity still available in your records",
    nextCollection: "Next collection",
    noCollection: "No collection is scheduled yet",
    collectionHint: "Kuapa Dwaso will confirm the date and collection point with you.",
    latestOffer: "Latest offer",
    noOffers: "No offer is ready yet",
    noOffersHint: "Your next offer will appear here when Kuapa Dwaso records it.",
    payment: "Payment",
    noPayment: "No payment is due yet",
    support: "Need help?",
    supportHint: "Speak with Kuapa Dwaso about your maize or payment.",
  },
  maize: {
    eyebrow: "Your stock",
    title: "My maize",
    intro: "See what quantity Kuapa Dwaso has recorded for you.",
    received: "Received",
    available: "Available",
    quality: "Quality",
    added: "Added",
    noMaize: "No maize record yet",
    noMaizeHint: "When Kuapa Dwaso records your maize, it will appear here.",
    viewRecord: "View record",
  },
  offers: {
    eyebrow: "From Kuapa Dwaso",
    title: "Your offers",
    intro: "Review the quantity, price, deductions, collection, and payment details.",
    noOffers: "No offers yet",
    noOffersHint: "Your offer will appear here when Kuapa Dwaso is ready to buy your maize.",
    offer: "Maize offer",
    acceptedQuantity: "Accepted quantity",
    price: "Price",
    deductions: "Deductions",
    netAmount: "You receive",
    collectionDate: "Collection date",
    collectionPoint: "Collection point",
    paymentDate: "Payment date",
    toBeConfirmed: "To be confirmed by Kuapa Dwaso",
    paymentRecorded: "Payment recorded",
    contact: "Contact Kuapa Dwaso",
    back: "Back to offers",
  },
  payments: {
    eyebrow: "Your money",
    title: "Payments",
    intro: "See what is due and what Kuapa Dwaso has paid.",
    due: "Due to you",
    paid: "Paid",
    paymentHistory: "Payment history",
    noPayments: "No payments yet",
    noPaymentsHint: "Payment updates will appear here after an offer is recorded.",
    viewOffer: "View offer",
  },
  support: {
    eyebrow: "Kuapa Dwaso support",
    title: "Contact us",
    intro: "Call or message us when you need help with your maize, collection, or payment.",
    call: "Call Kuapa Dwaso",
    message: "WhatsApp Kuapa Dwaso",
    unavailable: "A support contact will appear here when one is assigned to you.",
    hours: "Support hours: Monday to Saturday, 7:00 AM to 5:00 PM.",
  },
} as const;
