apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: <prod-cloudflare-tunnel-id>
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: <your-production-domain>
        service: http://www:3000
      - hostname: app.<your-production-domain>
        service: http://app:3000
      - hostname: admin.<your-production-domain>
        service: http://admin:3000
      - hostname: ops.<your-production-domain>
        service: http://ops:3000
      - hostname: api.<your-production-domain>
        service: http://api:4000
      - service: http_status:404
