apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kuapa-dwaso-production

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      group: secrets.infisical.com
      version: v1beta1
      kind: InfisicalAuth
      name: kuapa-dwaso-infisical
    patch: |-
      - op: replace
        path: /spec/infisicalConnectionRef/namespace
        value: kuapa-dwaso-production
      - op: replace
        path: /spec/universal/clientIdRef/namespace
        value: kuapa-dwaso-production
      - op: replace
        path: /spec/universal/clientSecretRef/namespace
        value: kuapa-dwaso-production
  - target:
      group: secrets.infisical.com
      version: v1beta1
      kind: InfisicalStaticSecret
      name: kuapa-dwaso-runtime
    patch: |-
      - op: replace
        path: /spec/infisicalAuthRef/namespace
        value: kuapa-dwaso-production
      - op: replace
        path: /spec/sources/0/projectId
        value: 1b3b07fb-3a1e-472b-be1c-8a21557f77b9
      - op: replace
        path: /spec/sources/0/environmentSlug
        value: prod
      - op: replace
        path: /spec/targets/0/namespace
        value: kuapa-dwaso-production
      - op: replace
        path: /spec/targets/1/namespace
        value: kuapa-dwaso-production

images:
  - name: ghcr.io/kuapa-dwaso/www
    newName: ghcr.io/kuapa-dwaso/www
    newTag: production
  - name: ghcr.io/kuapa-dwaso/app
    newName: ghcr.io/kuapa-dwaso/app
    newTag: production
  - name: ghcr.io/kuapa-dwaso/admin
    newName: ghcr.io/kuapa-dwaso/admin
    newTag: production
  - name: ghcr.io/kuapa-dwaso/ops
    newName: ghcr.io/kuapa-dwaso/ops
    newTag: production
  - name: ghcr.io/kuapa-dwaso/api
    newName: ghcr.io/kuapa-dwaso/api
    newTag: production
