FROM node:22-bookworm-slim AS builder

WORKDIR /repo

ENV CI=true
ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps ./apps
COPY packages ./packages
COPY convex ./convex

RUN corepack pnpm install --frozen-lockfile

ARG PACKAGE_NAME
ARG NEXT_PUBLIC_CONVEX_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_ENABLE_DEV_ACTOR_FALLBACK=false
ARG NEXT_PUBLIC_PREVIEW_ACCESS_ENABLED=false
ARG NEXT_PUBLIC_PREVIEW_PROGRAMME_ID=
ARG NEXT_PUBLIC_PREVIEW_PROFILE_ASSET_BASE_URL=
ARG START_COMMAND

ENV NODE_ENV=production
ENV NEXT_PUBLIC_CONVEX_URL=$NEXT_PUBLIC_CONVEX_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_ENABLE_DEV_ACTOR_FALLBACK=$NEXT_PUBLIC_ENABLE_DEV_ACTOR_FALLBACK
ENV NEXT_PUBLIC_PREVIEW_ACCESS_ENABLED=$NEXT_PUBLIC_PREVIEW_ACCESS_ENABLED
ENV NEXT_PUBLIC_PREVIEW_PROGRAMME_ID=$NEXT_PUBLIC_PREVIEW_PROGRAMME_ID
ENV NEXT_PUBLIC_PREVIEW_PROFILE_ASSET_BASE_URL=$NEXT_PUBLIC_PREVIEW_PROFILE_ASSET_BASE_URL
ENV START_COMMAND=$START_COMMAND

RUN corepack pnpm --filter "$PACKAGE_NAME" build

FROM node:22-bookworm-slim AS runtime

WORKDIR /repo

ARG START_COMMAND

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV START_COMMAND=$START_COMMAND

RUN corepack enable

COPY --from=builder /repo /repo

EXPOSE 3000
EXPOSE 4000

CMD ["sh", "-c", "$START_COMMAND"]
