apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: <staging-cloudflare-tunnel-id>
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: staging.<your-domain>
        service: http://www:3000
      - hostname: app.staging.<your-domain>
        service: http://app:3000
      - hostname: admin.staging.<your-domain>
        service: http://admin:3000
      - hostname: ops.staging.<your-domain>
        service: http://ops:3000
      - hostname: api.staging.<your-domain>
        service: http://api:4000
      - service: http_status:404
