apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kuapa-dwaso-staging

resources:
  - ../../base
  - namespace.yaml
  - infisical-cluster-role-binding.yaml

patches:
  - path: cloudflared-config.yaml
  - target:
      group: secrets.infisical.com
      version: v1beta1
      kind: InfisicalAuth
      name: kuapa-dwaso-infisical
    patch: |-
      - op: replace
        path: /spec/infisicalConnectionRef/namespace
        value: kuapa-dwaso-staging
      - op: replace
        path: /spec/kubernetes/identityIdRef/namespace
        value: kuapa-dwaso-staging
      - op: replace
        path: /spec/kubernetes/serviceAccountRef/namespace
        value: kuapa-dwaso-staging
  - target:
      group: secrets.infisical.com
      version: v1beta1
      kind: InfisicalStaticSecret
      name: kuapa-dwaso-runtime
    patch: |-
      - op: replace
        path: /spec/infisicalAuthRef/namespace
        value: kuapa-dwaso-staging
      - op: replace
        path: /spec/sources/0/projectSlug
        value: <infisical-project-slug>
      - op: replace
        path: /spec/sources/0/environmentSlug
        value: staging
      - op: replace
        path: /spec/targets/0/namespace
        value: kuapa-dwaso-staging

images:
  - name: ghcr.io/kuapa-dwaso/www
    newName: ghcr.io/kuapa-dwaso/www
    newTag: staging
  - name: ghcr.io/kuapa-dwaso/app
    newName: ghcr.io/kuapa-dwaso/app
    newTag: staging
  - name: ghcr.io/kuapa-dwaso/admin
    newName: ghcr.io/kuapa-dwaso/admin
    newTag: staging
  - name: ghcr.io/kuapa-dwaso/ops
    newName: ghcr.io/kuapa-dwaso/ops
    newTag: staging
  - name: ghcr.io/kuapa-dwaso/api
    newName: ghcr.io/kuapa-dwaso/api
    newTag: staging
